services:
  - type: web
    name: text-editor-pwa
    env: node
    plan: free
    buildCommand: npm install --prefix Develop/client && npm install --prefix Develop/server && npm run build --prefix Develop/client
    startCommand: npm run start --prefix Develop/server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000